config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  post 'auth/steam/callback' => 'welcome#auth_callback'
  get 'login' => 'welcome#login'
  delete 'logout', :controller => 'welcome', :action => 'logout'
  get 'account' => "accounts#show"
  get 'conversations' => "conversations#show"

  post '/profiles/:id', to: 'profiles#show'

  get '/payment/success', to: 'payment#success'
  match '/payment/failure'  => 'payment#failure', via: [:get, :post]
  get '/payment/pay', to: 'payment#pay'

  resources :profiles, only: [:show,:edit,:update] do
		member do
			get 'populate_coaches'
			get 'new_add_coach'
			put 'add_coach'
			put 'send_friend_request'
			get 'populate_reviews'
      put 'verify_mmr'
      put 'verify'
      put 'un_verify'
		end
	end

	resources :friends, only: [:index] do
		member do
			put 'send_request'
			put 'cancel_request'
			put 'decline_request'
			get 'requests'
			put 'accept_request'
		end
	end

	resources :coaches, only: [:index, :new, :create] do
		member do
			put 'free_request'
			put 'accept_free_request'
			put 'cancel_free_request'
			put 'decline_free_request'
			get 'review_rating'
			get 'sign_in'
			put 'add_review_rating'
		end
	end

	resources :notifications, only: [:show] do
		member do
			get 'friend_requests'
			get 'free_coaching_requests'
			get 'coaching_requests'
		end
	end

  resources :conversations
  resources :messages
  resources :search
  resources :contact

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :populate_user
  skip_before_filter :verify_authenticity_token, :only => :show

  before_filter :set_cache_buster

  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

  def show
  end

  def edit
  end

  def populate_profile
  end

  def populate_coaches
    @coach_data = @user.coached_by_data
  end

  def populate_reviews
    @coach_data = @user.coach_of_data
  end

  def verify_mmr
    @user.update(mmr_verified: true)
  end

  def verify
    @user.update(is_verified: true)
  end

  def un_verify
    @user.update(is_verified: false)
  end

  def update
    user_attributes = user_params
    user_attributes['mmr']=user_attributes['mmr'].to_i
    user_attributes['coaching_rate']=user_attributes['coaching_rate'].to_i
    user_attributes['is_a_coach']=user_attributes['is_a_coach'] == 'true'
    user_attributes['provides_free_coahing'] = user_attributes['provides_free_coahing'] == "true"
    if @user.update(user_attributes)
      render 'populate_profile.js'
    else
      render 'edit.js'
    end
  end

  private
  def populate_user
    @user = User.find_by(steam_id: params[:id])
    @user.languages = [] if @user.languages.nil?
    @user.regions = [] if @user.regions.nil?
  end

  def user_params
    params.require(:user).permit(:mmr, :is_a_coach, :dota_buff_link,:about_me,:coaching_rate, :provides_free_coahing, regions: [], languages: [])
  end

end

app/views/profiles/_add_coach.html.erb
<%=form_for @user, url:add_coach_profile_path(id: @user.steam_id), method: :put, remote: true  do |u|%>
	<div class="form-group row">
		<%=u.label :coached_by%>
		<%=u.collection_select(:coached_by, @potential_coaches, :steam_id, :steam_nickname, :prompt => "Select a coach") %>
	</div>
	<div class="modal-footer">
		<%=u.submit "Add as Coach", class: "btn btn-primary", data: {disable_with: "Processing..."}%>
		<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
	</div>
<%end%>

app/views/profiles/_coaches.html.erb
<h1 class="page-title">My Coaches</h1>
<div id="accordion" class="parent_width">
	<%@coach_data.each do |data|%>
		<h3><%=link_to data.coached_by.steam_nickname, profile_path(id: data.coached_by.steam_id)%></h3>
		<div>
			<%=link_to "Coach Profile" , profile_path(id: data.coached_by.steam_id), :class => "blue" , :target => "_blank" %>
            <br/>
            <br/>
			<ul>
				<%data.sessions.each do |session|%>
					<li>
					$<%=session.total_fees%> paid on <%=Time.at(session.since).strftime("%B %e, %Y at %I:%M %p")%> for <%=session.hours%> hour(s): 
					<%=link_to "Review", review_rating_coach_path(id: data.coached_by.steam_id,uuid: session.uuid), remote: true, class: "btn btn-primary"%>
					</li>
                  <br/>
				<%end%>
			</ul>
		</div>
	<%end%>
</div>

app/views/profiles/_profile_form.html.erb
<div class="form">
<div class = "form-row">
		<%=image_tag(session[:current_user]['image'])%>
		<%=session[:current_user]['nickname']%>
</div>
<%=form_for user, url: profile_path(id: user.steam_id), remote: true, method: :put do |u|%>
	<div class = "form-row">
		<div class= "form-col">
			<%=u.label :mmr %>
			<%=u.number_field :mmr %>
		</div>
		<div class= "form-col">
			<%=u.label :is_a_coach %>
			<%=u.radio_button :is_a_coach, 'true' %>
			<%= "Yes"%>
			<%=u.radio_button :is_a_coach, 'false' %>
			<%= "No"%>
		</div>
	</div>
	<div class="form-row">
		<div class= "form-col">
			<%=u.label :dota_buff_link %>
			<%=u.url_field :dota_buff_link %>
		</div>
		<div class= "form-col" id="coaching_rate">
			<%=u.label :coaching_price, 'Coaching Price per hour' %>
			<%=u.number_field :coaching_rate %>$
		</div>
	</div>
	<div class="form-row">
		<div class="form-col">
		</div>
		<div class= "form-col" id="free_coaching">
			<%=u.label :provides_free_coahing %>
			<%=u.radio_button :provides_free_coahing, 'true' %>
			<%= "Yes"%>
			<%=u.radio_button :provides_free_coahing, 'false' %>
			<%= "No"%>
		</div>
	</div>
	<div class="form-row">
		<div class="form-col">
			<%=u.label :regions%>
		</div>
		<div class="region-list">
			<%Regions.first.names.each do |region|%>
				<div class="region-list-option">
					<%= check_box_tag "user[regions][]", region, u.object.regions.include?(region)%>
					<%=region%>
				</div>
			<%end%>
		</div>
	</div>
	<div class="form-row">
		<div class="form-col">
			<%=u.label :languages%>
		</div>
		<div class="language-list">
			<%Languages.first.names.each do |language|%>
				<div class="language-list-option">
					<%= check_box_tag "user[languages][]", language, u.object.languages.include?(language)%>
					<%=language%>
				</div>
			<%end%>
		</div>
	</div>
	<div class="form-row">
		<div class= "about-me">
			<%=u.label :about_me %>
            <%=u.text_area :about_me,  :placeholder => "Make sure you mention about your availabilty timings.." %>
		</div>
	</div>
	<%=u.submit "Save", class: "btn btn-primary"%>
	<%=link_to "Cancel", profile_path(user.steam_id), class: "btn btn-default", remote: true%>
<%end%>
</div>

app/views/profiles/_reviews.html.erb
<h1 class="page-title">Review & Rating</h1>
<div class = "row">
	<div class="col-lg-6">
		<label class="heading">Average Rating: </label>
		<%if user.average_rating > 0%>
			<%=user.average_rating.round(2)%>
		<%else%>
			TBD
		<%end%>
	</div>
</div>
<br/>
<%if user.has_both_review%>
	<div class="row">
		<div class="col-lg-5">
			<label class="heading">Best Rating:</label>
			<%=user.best_rating%>
			<br/>
			<label class="heading">Review:</label>
			<%=user.best_review%>
		</div>
      <br/>
		<div class="col-lg-2">

			vs

		</div>
      <br/>
		<div class="col-lg-5">
			<label class="heading">Worst Rating:</label>
			<%=user.worst_rating%>
			<br/>
			<label class="heading">Review:</label>
			<%=user.worst_review%>
		</div>
	</div>
<%end%>
<br/>


<% if @coaches_data != nil %>
    <h3 class="heading">All Reviews</h3>
<% end %>

<div id="accordion" class="parent_width">
	<%coach_data.each do |data|%>
		<h3><%=link_to data.coached_to.steam_nickname, profile_path(id: data.coached_to.steam_id)%></h3>
		<div>
          <!--todo: removing profile link as this is too much info at the moment, will introduce later if necessary-->
			<!--<%=link_to "Profile", profile_path(id: data.coached_to.steam_id)%>-->
			<ul>
				<%data.sessions.each do |session|%>
					<%unless session.rating.blank?%>
						<li>
						Rating: <span class="small-text"><%=session.rating%></span>
                            ||
						<%unless session.review.blank?%>
							Review: <span class="small-text"><%=session.review%></span>
						<%end%>
						</li>

					<%end%>
				<%end%>
			</ul>
		</div>
	<%end%>
</div>

app/views/profiles/_show.html.erb
<section class="profile-wrapper">
	<div class="profile-innerwrapper">
	<aside class="profile-menu sidebar-offcanvas" id="sidebar" role="navigation">
		<ul class="nav">
			<li class="active"><%=link_to "Profile", profile_path, remote: true%></li>
			<li><%=link_to "My Coaches", populate_coaches_profile_path(id: user.steam_id), remote: true if user.same_as(session[:current_user])%></li>
		    <li><%=link_to "Reviews & Ratings", populate_reviews_profile_path(id: user.steam_id), remote: true if user.is_a_coach%></li>
		</ul>
	</aside>
	<div class="profile-details" id="content">
		<%=render partial: "profile", locals: {user: user}%>
	</div>
	</div>
</section>

app/views/profiles/add_coach.js.erb
(function(){
	$('#modal_window').modal('hide');
})();

app/views/profiles/edit.js.erb
(function(){
	$("#content").html("<%=j render partial: "profile_form", locals: {user: @user}%>");
	enable_coaching_rate();
})();

app/views/profiles/new_add_coach.js.erb
(function(){
	populateModalWindow("Add a coach","<%= j render 'add_coach', locals: {friends: @friends}%>")
})();

app/views/profiles/populate_coaches.js.erb
(function(){
	$("#content").html("<%=j render partial: "coaches", locals: {user: @user}%>")
	$("#accordion").accordion({
		collapsible: true
	});
})();

app/views/profiles/populate_profile.js.erb
(function(){
	$("#content").html("<%=j render partial: "profile", locals: {user: @user}%>")
})();

app/views/profiles/populate_reviews.js.erb
(function(){
	$("#content").html("<%=j render partial: "reviews", locals: {coach_data: @coach_data, user: @user}%>")
	$("#accordion").accordion({
		collapsible: true
	});
})();

app/views/profiles/show.html.erb
<%= render partial: "show", locals: {user: @user}%>

app/views/profiles/verify.js.erb
(function(){
	$("#content").html("<%=j render partial: "profile", locals: {user: @user}%>");
})();

app/views/profiles/verify_mmr.js.erb
(function(){
	$("#content").html("<%=j render partial: "profile", locals: {user: @user}%>");
})();