config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  post 'auth/steam/callback' => 'welcome#auth_callback'
  get 'login' => 'welcome#login'
  delete 'logout', :controller => 'welcome', :action => 'logout'
  get 'account' => "accounts#show"
  get 'conversations' => "conversations#show"

  post '/profiles/:id', to: 'profiles#show'

  get '/payment/success', to: 'payment#success'
  match '/payment/failure'  => 'payment#failure', via: [:get, :post]
  get '/payment/pay', to: 'payment#pay'

  resources :profiles, only: [:show,:edit,:update] do
		member do
			get 'populate_coaches'
			get 'new_add_coach'
			put 'add_coach'
			put 'send_friend_request'
			get 'populate_reviews'
      put 'verify_mmr'
      put 'verify'
      put 'un_verify'
		end
	end

	resources :friends, only: [:index] do
		member do
			put 'send_request'
			put 'cancel_request'
			put 'decline_request'
			get 'requests'
			put 'accept_request'
		end
	end

	resources :coaches, only: [:index, :new, :create] do
		member do
			put 'free_request'
			put 'accept_free_request'
			put 'cancel_free_request'
			put 'decline_free_request'
			get 'review_rating'
			get 'sign_in'
			put 'add_review_rating'
		end
	end

	resources :notifications, only: [:show] do
		member do
			get 'friend_requests'
			get 'free_coaching_requests'
			get 'coaching_requests'
		end
	end

  resources :conversations
  resources :messages
  resources :search
  resources :contact

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_action :populate_user
	before_action :populate_notification, only: [:coaching_requests]
	before_action :populate_friend_requests, only: [:friend_requests, :show]
	before_action :populate_friend_request_count, only: [:friend_requests, :show]
	before_action :populate_free_coaching_requests, only: [ :show, :coaching_requests]
	before_action :populate_free_coaching_request_count, only: [ :show, :coaching_requests]
	before_action :friend_request_seen, only: [:show, :friend_requests]
	before_action :coaching_notification_seen, only: [:coaching_requests]

	def friend_requests
	end

	def show
	end

	def coaching_requests
	end

	private
	def populate_user
		@user = User.find_by(steam_id: params[:id])
		@user.languages = [] if @user.languages.nil?
		@user.regions = [] if @user.regions.nil?
	end

	def populate_friend_requests
		@friend_requests = @user.friend_request
	end

	def populate_friend_request_count
		friend_requests_count = @user.friend_request_rels.count{|rel| rel.is_read == false}
		@formatted_friend_request_count=""
		@formatted_friend_request_count="(#{friend_requests_count})" if friend_requests_count > 0
	end

	def friend_request_seen
		@user.friend_request_rels.each {|req| req.update_attribute("is_read", true)}
	end

	def coaching_notification_seen
		@user.notifications.each {|n| n.update_attribute("is_read", true)}
		@user.coaching_request_rels.each {|req| req.update_attribute("is_read", true)}
	end

	def populate_free_coaching_requests
		@coaching_requests = @user.coaching_request
	end

	def populate_notification
		@notifications = @user.notifications.sort{|n| -n[:timestamp]}
	end

	def populate_free_coaching_request_count
		coaching_request_count = @user.coaching_request_rels.count{|rel| rel.is_read == false}
		notification_count = @user.notifications.find_all{|n| n.is_read == false}.count
		@formatted_coaching_request_count=""
		@formatted_coaching_request_count="(#{coaching_request_count+notification_count})" if coaching_request_count+notification_count > 0
	end

end

app/views/notifications/_coaching_requests.html.erb
<div>
<ul>
<%coaching_requests.each do |request|%>
	<li>
	<div class="notification-profile">
		<%=image_tag(request.steam_image, class: 'image')%> <%=request.steam_nickname%>
	</div>
	<div class="notification-btn-wrapper">
		<%=link_to "Accept", accept_free_request_coach_path(coach_id:session[:current_user]["uid"], coachee_id: request.steam_id ), method: :put,:class=>"primary-btn", remote: true%>
		<%=link_to "Decline", decline_free_request_coach_path(coach_id:session[:current_user]["uid"], coachee_id: request.steam_id ), method: :put, :class=>"secondary-btn", remote: true%>
	</div>
	</li>
<%end%>
</ul>
<ul>
<%notifications.each do |notification|%>
	<li>
	<div>
		<%=notification.body%> on <%=Time.at(notification.timestamp).strftime("%B %e, %Y at %I:%M %p")%>
	</div>
	</li>
<%end%>
</ul>

app/views/notifications/_friend_request.html.erb
<ul>
<%friend_requests.each do |request|%>
	<li>
	<div class="notification-profile">
		<%=image_tag(request.steam_image, class: 'image')%> <%=request.steam_nickname%>
	</div>
	<div class="notification-btn-wrapper">
		<%=link_to "Accept", accept_request_friend_path(id:session[:current_user]["uid"], friend_id: request.steam_id ), :class=>"primary-btn" ,method: :put, remote: true%>
		<%=link_to "Decline", decline_request_friend_path(id:session[:current_user]["uid"], friend_id: request.steam_id ), :class=>"secondary-btn" ,method: :put, remote: true%>
	</div>
	</li>
<%end%>
</ul>

app/views/notifications/_show.html.erb
<div class="container notification">

  <aside class="notification-menu" id="sidebar" role="navigation">
    <ul class="nav">
      <li class="active"><%= link_to "Friend Requests"+@formatted_friend_request_count, friend_requests_notification_path, id: "friend_requests", remote: true if user.same_as(session[:current_user]) %></li>
      <li><%= link_to "Coaching Notifications"+@formatted_coaching_request_count, coaching_requests_notification_path(id: user.steam_id),  id: "coaching_notifications", remote: true %></li>
    </ul>
  </aside>
  <div class="profile-innerwrapper">
    <h1 class="page-title">Notifications</h1>
    <div class="notification-details" id="content">
      <%= render partial: "friend_request", locals: {friend_requests: friend_requests} %>
    </div>
  </div>
</div>

app/views/notifications/coaching_requests.js.erb
(function(){
	$("#content").html("<%=j render partial: "coaching_requests", locals: {user: @user, notifications: @notifications, coaching_requests: @coaching_requests}%>")
})();

app/views/notifications/friend_requests.js.erb
(function(){
	$("#content").html("<%=j render partial: "friend_request", locals: {friend_requests: @friend_requests}%>")
})();

app/views/notifications/show.html.erb
<%= render partial: "show", locals: {user: @user, friend_requests: @friend_requests}%>

app/views/notifications/show.js.erb
(function(){
	$("#home").html("<%=j render partial: "show", locals: {user: @user, friend_requests: @friend_requests}%>");
    highlightActiveMenu();
    $("#coaching_notifications").click(function(){
        $("#coaching_notifications").text('Coaching Notifications');
    });
})();